project:
  type: website
  render:
    - "*.qmd"
    - "HobbyEEProjects/*.qmd"
format-links: true
prefer-html: true
license: "CC by"
copyright:
  holder: Gaelen Guzman
  year: 2025
website:
  title: "Gaelen Guzman"
  repo-url: https://github.com/gaelenDG/GaelenGuzman.github.io
  repo-actions: [source, issue]
  # favicon: assets/images/icon.svg
  navbar:
    pinned: true
    # logo: assets/images/logo.png
    right:
      - text: "Resume"
        href: assets/cv/GaelenGuzman_Resume.pdf
        target: "_blank"
    left: 
      - text: "<i class='fa-solid fa-flask-vial'></i> Research Projects"
        menu:
          - text: "The Lipid Interactome"
            href: https://www.lipidinteractome.org
            target: "_blank"
          - text: "TB & The Sphinx (My dissertation)"
            href: https://guzmangadissertation.netlify.app
            target: "_blank"
      - text: "<i class='fa-solid fa-microchip'></i> Hobby Electronics Projects"
        menu:
          - href: HobbyEEProjects/MushroomLamp_v1.qmd
            text: "Mushroom Lamp"
          - href: HobbyEEProjects/LightUpBabyBook.qmd
            text: "Light-up Baby Book"
          - href: HobbyEEProjects/MushroomLamp_v2.qmd
            text: "Mushroom Lamp v2"
          - href: HobbyEEProjects/MagneticStirbarLamp.qmd
            text: "Magnetic Stirbar Lamp"
          - href: HobbyEEProjects/SunnysideElectricityPresentations/Electricity1_presentation.qmd
            text: "Sunnyside Intro to Electronics #1"
  sidebar: true 
  page-navigation: true
  page-footer:
    center:
      - text: "Â© 2025 Gaelen Guzman | Built with Quarto"
      

format:
  html:
    lightbox:
      match: auto
      effect: fade
      desc-position: bottom
      loop: true
    mainfont: Charter
    theme: [Flatly, assets/custom_theme.scss]
    css: assets/css/styles.css
    toc: true
    sidebar: true
    include-in-header: 
      - text: |
          <script src="https://kit.fontawesome.com/f829805578.js" crossorigin="anonymous"></script>
